### ISSUE TITLE
Twitter share count don't show now

### ISSUE THREAD

**Issue by enjoyiacm** [AyumuKasuga/SocialShare#12]
Hey @AyumuKasuga 

At 20 Nov 2015 Twitter no longer support API 1.0.
I found in API 1.1 new way to get it: https://dev.twitter.com/rest/reference/get/search/tweets

Fix, please.

**Comment by AyumuKasuga** [comment]
Because if that https://blog.twitter.com/2015/hard-decisions-for-a-sustainable-platform
Count API was an unofficial API and now url does not work :crying_cat_face: 
I just remove support twitter counter. Of course you can still use twitter button for sharing, but without counter. Official new twitter buttons do not have counter too.

**Comment by enjoyiacm** [comment]
Yep. Very sad news..
